### ISSUE TITLE
Save the dashboard automatically upon closing

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#240]
As described in another issue (https://github.com/neo4j-labs/neodash/issues/238#issuecomment-1289290775), I lost a few days worth of work after deleting cookies from my browser, because I do/did not save the dashboard after every modification.
I now checked the documentation again and I cannot find any warning about this lurking danger anywhere (at least not in plain sight, but I might have overlooked it).
So I have 2 requests:

1. please add a clear warning in the documentation: cookies gone equals dashboard gone!
2. please consider adding a feature to the General Settings: "Save dashboard when closing?" which eliminates a lot of work as well as destruction-by-forgetfulness.

Thank you.

**Comment by BennuFire** [comment]
Hi @gcthys ,

We just added a warning on the documentation (https://neo4j.com/labs/neodash/2.1/user-guide/dashboards/) on the Save a Dashboard section. We are not considering automatic saving actions for now due to the security considerations that this may open.

Thanks for your suggestion and sorry for the inconvenience this may have caused.

Harold
