### ISSUE TITLE
Add advanced setting to line charts to turn it into a scatter plot

### ISSUE THREAD

**Issue by nielsdejong** [neo4j-labs/neodash#323]
Since a scatter plot is a sub-class of a line chart (without lines), we can extend the line chart to become a scatter plot if displaying lines is disabled.

**Comment by JonanOribe** [comment]
Could I talke this one?

**Comment by JonanOribe** [comment]
@nielsdejong,  after make a look to the code, I found that if you set lineWidth to 0, you have a scatter plot.

![image](https://user-images.githubusercontent.com/11914201/216046770-5f6464c5-ffd7-424c-8058-ef82446f04a4.png)

![image](https://user-images.githubusercontent.com/11914201/216046420-043378da-0a43-403b-b9ee-e927b3df53ab.png)

So, it is possible to create a new component just for scatter plot or simply, when an user selects Scatter instead of Linear on the table, the dashboard creates a Linear component with 0 line width.

![image](https://user-images.githubusercontent.com/11914201/216047246-d8bf769c-da9e-4530-903a-3ec028ce3eee.png)

What do you prefer??

**Comment by nielsdejong** [comment]
Hi @JonanOribe - Thanks for picking this up!
I like your second suggestion:
> when an user selects Scatter instead of Linear on the table, force the dashboard to create a Linear Component with 0 line width.

that would save us a lot of extra code and keep the UI simpler by having one less element in the list of charts.

**Comment by JonanOribe** [comment]
Hi, I'm trying to update the Charts interface to be able to get "label" property, but I think that I'm missing something, because the interface still get the other values, but not "label". Any idea??

![image](https://user-images.githubusercontent.com/11914201/216356283-2a89185f-784a-446d-a393-3006b53b7151.png)

![image](https://user-images.githubusercontent.com/11914201/216356394-5b3865b2-9d77-4418-9259-fb86ebfaec71.png)

![image](https://user-images.githubusercontent.com/11914201/216356735-c8c0cfb0-c2a3-4133-9b5a-607973818335.png)

**Comment by nielsdejong** [comment]
Hi @JonanOribe ,
Perhaps it's better to use the advanced settings for this one?
You could add a new entry here:
https://github.com/neo4j-labs/neodash/blob/master/src/config/ReportConfig.tsx#L655

```
  type: {
        label: 'Plot Type',
        type: SELECTION_TYPES.LIST,
        values: ['line', 'scatter'],
        default: 'line',
      },
```
And then use `settings.line` inside `LineChart.tsx` to override the line width to zero. What do you think?

**Comment by JonanOribe** [comment]
Finally, I found your approach as the simpler one, thanks!. The PR is ready
