### ISSUE TITLE
[Feature request] select component: selecting a prop available in DB, rather then from a single node label

### ISSUE THREAD

**Issue by ksipma** [neo4j-labs/neodash#370]
Consider the following use case:

I want to select nodes by an uuid field which I created. However autocomplete requires me to select a node label first. I have the uuid field over multiple node label types. How it is designed I cannot use this component. A wildcard or (all) as a selector would really help me.

**Comment by BennuFire** [comment]
Hi @ksipma ,

We strongly suggest to bind a property to a node label in order to be able to use an index on it (Assuming you created one before) otherwise the query may not be performant. In any case, if you really want to use implement a search that way, you can use the new Query type of Parameter selector just released with 2.2.4. 

I'll close this but let me know if there's any issue with it.

Harold
