### ISSUE TITLE
Specify local path instead of an url link in iFrame

### ISSUE THREAD

**Issue by Robiedibob** [neo4j-labs/neodash#441]
At this moment you can only specify an URL in iFrame.
Would be nice to have the possibility to specify a local path to your local pictures or documents

Dealing with projects which pictures are not allowed to be on the internet.

**Comment by mariusconjeaud** [comment]
Technically, an iframe can take a path like "file:///xxx.png" (not in NeoDash because we check for `http` and `https`).

But accessing local resources in this way is forbidden by web browsers for security reasons. One way to go is to start a local server serving these files ; then you can load them through a http scheme. See [this thread here](https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource).
