### ISSUE TITLE
Dark mode turns text in reports illegible

### ISSUE THREAD

**Issue by gcthys** [neo4j-labs/neodash#569]
Compare the following screen prints of the same report fragments:
![Schermafbeelding 2023-08-16 114123](https://github.com/neo4j-labs/neodash/assets/68611501/008a8e54-f4e1-4f0e-9bd4-9bba72552f18)

![Schermafbeelding 2023-08-16 114032](https://github.com/neo4j-labs/neodash/assets/68611501/87119a7e-36a7-43ab-b748-be50bf946272)

I modified the lumen threshold in general settings (default on 25, tried 0 and 100) but that had no effect.

**Comment by BennuFire** [comment]
Titles aligned black on 2.3.3

**Comment by gcthys** [comment]
Hi @BennuFire ,
sorry, but even more black text turns white in dark mode, please compare the previous screen print with this one:

![image](https://github.com/neo4j-labs/neodash/assets/68611501/66af0b24-79b0-4b2f-823f-0fecec07794d)

**Comment by BennuFire** [comment]
Titles got aligned with default color of the Theme. Keep in mind that texts within cards are not aware of custom backgrounds so they will not adapt in order to turn visible. I don't see in the immediate future a text color adjustment of the text based on current theme + custom background.

If you are planning to keep using the dark theme, I suggest you to change the custom background color for the moment.

**Comment by gcthys** [comment]
@BennuFire : thanks for the clarification.
I won't be using the dark mode then because there is only one way of keeping different types of reports on one page apart and that is the custom background colour.

Might be handy to mention in the documentation not to apply custom background colours when using the dark mode!
